"""
Code Review Agent.

Fetches a PR diff via MCP, uses the pre-fetched RAG context for codebase
awareness, invokes GPT-4o with a structured code review prompt, parses the
JSON response, and posts a formatted markdown comment back to GitHub.
"""

import json
from typing import Any

from langchain_core.messages import HumanMessage, SystemMessage

from orchestrator.agents.base import BaseAgent
from orchestrator.graph.state import (
    CodeIssue,
    CodeReviewResult,
    NexusState,
    RAGContext,
)

_SEVERITY_EMOJI = {
    "critical": "🔴",
    "high": "🟠",
    "medium": "🟡",
    "low": "🔵",
}

_SYSTEM_PROMPT = """\
You are an expert code reviewer. You have been given a pull request diff and
relevant context from the existing codebase (retrieved via semantic search).

Your task is to find ALL of the following issues in the diff:
1. **Security vulnerabilities**: SQL injection, XSS, hardcoded secrets, auth bypass,
   insecure deserialization, path traversal, SSRF, missing input validation.
2. **Performance problems**: N+1 database queries, blocking I/O inside async
   functions (time.sleep, requests.get, synchronous file I/O), missing database
   indexes for queried columns, inefficient loops.
3. **Correctness bugs**: Off-by-one errors, null dereferences, incorrect error
   handling, race conditions, incorrect type assumptions.
4. **Style inconsistencies**: Deviations from patterns seen in the retrieved
   codebase context (naming conventions, module structure, docstring format).

You MUST respond with a single JSON object — no markdown, no explanation — in
exactly this format:
{
  "issues": [
    {
      "severity": "critical" | "high" | "medium" | "low",
      "file": "<filename>",
      "line": <integer>,
      "message": "<clear description of the issue>",
      "suggestion": "<concrete code fix>"
    }
  ],
  "summary": "<1-3 sentence overall assessment>",
  "approved": <true if no critical/high issues, false otherwise>
}

If the diff is clean, return an empty issues array and approved=true.
"""


def _format_pr_comment(result: CodeReviewResult) -> str:
    """
    Render a CodeReviewResult as a structured GitHub markdown comment.

    Args:
        result: The parsed code review result.

    Returns:
        Markdown-formatted comment body ready for posting to GitHub.
    """
    lines = ["## 🤖 Nexus Code Review\n"]

    if result.approved:
        lines.append("✅ **Approved** — No blocking issues found.\n")
    else:
        lines.append("❌ **Changes Requested** — Blocking issues detected.\n")

    lines.append(f"**Summary:** {result.summary}\n")

    if not result.issues:
        lines.append("\n_No issues found. Ship it! 🚀_")
        return "\n".join(lines)

    lines.append(f"\n### Issues Found ({len(result.issues)})\n")

    # Group by severity for better readability
    for severity in ("critical", "high", "medium", "low"):
        severity_issues = [i for i in result.issues if i.severity == severity]
        if not severity_issues:
            continue
        emoji = _SEVERITY_EMOJI[severity]
        lines.append(f"#### {emoji} {severity.capitalize()} ({len(severity_issues)})\n")
        for issue in severity_issues:
            lines.append(f"**`{issue.file}` line {issue.line}:** {issue.message}")
            lines.append(f"\n```suggestion\n{issue.suggestion}\n```\n")

    lines.append(
        "\n---\n_Generated by [Nexus](https://github.com/your-org/nexus). "
        "This review is AI-assisted — please verify suggestions before merging._"
    )
    return "\n".join(lines)


class CodeReviewAgent(BaseAgent):
    """
    Automated code review agent for GitHub pull requests.

    Workflow:
    1. Fetch the PR diff via the GitHub MCP server.
    2. Use rag_context already in state for codebase awareness.
    3. Invoke GPT-4o with structured prompt demanding JSON output.
    4. Parse and validate the JSON response.
    5. Post a formatted markdown comment to the PR.
    6. Return a CodeReviewResult to update the shared state.
    """

    async def run(self, state: NexusState) -> dict:
        """
        Execute the full code review pipeline.

        Args:
            state: Current NexusState (must have event.payload with pr data).

        Returns:
            State update dict with ``code_review_result`` and ``tool_calls``.
        """
        event = state["event"]
        payload = event.payload

        pr_data = payload.get("pull_request", {})
        pr_number = int(pr_data.get("number", payload.get("pr_number", 0)))
        repo = (
            payload.get("repository", {}).get("full_name")
            or f"{self.settings.github_org}/{self.settings.github_repo}"
        )

        self.log.info("code_review_started", repo=repo, pr_number=pr_number)

        # Step 1: Fetch PR diff
        diff: str = await self.mcp.call(
            "github",
            "get_pr_diff",
            {"repo": repo, "pr_number": pr_number},
        )

        # Truncate diffs that exceed token limits (~12k chars ≈ 3k tokens)
        if len(diff) > 12_000:
            self.log.warning(
                "diff_truncated",
                original_len=len(diff),
                truncated_len=12_000,
            )
            diff = diff[:12_000] + "\n\n[... diff truncated ...]"

        # Step 2: Build context from RAG results
        rag_context: RAGContext | None = state.get("rag_context")
        context_text = ""
        if rag_context and rag_context.retrieved_chunks:
            context_parts = [
                f"# {chunk.source_file}\n```{chunk.language}\n{chunk.content[:600]}\n```"
                for chunk in rag_context.retrieved_chunks[:5]
            ]
            context_text = (
                "## Relevant Codebase Context (for style consistency)\n\n"
                + "\n\n".join(context_parts)
            )

        # Step 3: Call GPT-4o
        user_message = (
            f"## Pull Request Diff\n\n```diff\n{diff}\n```\n\n{context_text}"
        )

        response = await self.llm.ainvoke(
            [
                SystemMessage(content=_SYSTEM_PROMPT),
                HumanMessage(content=user_message),
            ]
        )
        raw_response = str(response.content).strip()

        # Step 4: Parse JSON response
        try:
            # Strip markdown code fences if the model wrapped the JSON
            if raw_response.startswith("```"):
                raw_response = raw_response.split("```")[1]
                if raw_response.startswith("json"):
                    raw_response = raw_response[4:]
            parsed = json.loads(raw_response)
        except json.JSONDecodeError as exc:
            self.log.error(
                "code_review_json_parse_failed",
                error=str(exc),
                raw_len=len(raw_response),
            )
            # Return a safe fallback result rather than crashing the graph
            parsed = {
                "issues": [],
                "summary": "Code review parsing failed — manual review required.",
                "approved": False,
            }

        issues = [
            CodeIssue(
                severity=i.get("severity", "medium"),
                file=i.get("file", "unknown"),
                line=int(i.get("line", 0)),
                message=i.get("message", ""),
                suggestion=i.get("suggestion", ""),
            )
            for i in parsed.get("issues", [])
        ]

        result = CodeReviewResult(
            pr_number=pr_number,
            repo=repo,
            issues=issues,
            summary=parsed.get("summary", ""),
            approved=bool(parsed.get("approved", False)),
        )

        # Step 5: Post comment to GitHub
        comment_body = _format_pr_comment(result)
        await self.mcp.call(
            "github",
            "post_pr_comment",
            {"repo": repo, "pr_number": pr_number, "body": comment_body},
        )
        result.posted_to_github = True

        self.log.info(
            "code_review_complete",
            pr_number=pr_number,
            issues=len(issues),
            approved=result.approved,
        )

        return {
            "code_review_result": result,
            "tool_calls": self._drain_tool_logs(),
            "current_agent": "code_review",
        }
